apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "directus.core" . }}
  labels:
    app.kubernetes.io/name: {{ include "directus.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "directus.chart" . }}
data:
