apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "directus.core" . }}
  labels:
    {{- include "directus.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "directus.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "directus.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "directus.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- if .Values.initContainers }}
      initContainers:
        {{- include "directus.render" ( dict "value" .Values.initContainers "context" $ ) | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
            {{- range $val := .Values.attachExistingSecrets }}
            - secretRef:
                name: {{ $val }}
            {{- end }}
          env:
            - name: DB_CLIENT
              value: {{ include "directus.databaseClient" . | quote }}
            - name: DB_HOST
              value: {{ include "directus.databaseHost" . | quote }}
            - name: DB_PORT
              value: {{ include "directus.databasePort" . | quote }}
            - name: DB_DATABASE
              value: {{ include "directus.databaseName" . | quote }}
            - name: DB_USER
              value: {{ include "directus.databaseUser" . | quote }}
            - name: ADMIN_EMAIL
              value: {{ .Values.directus.adminEmail | quote }}
            - name: HOST
              value: "::"
            - name: REDIS_ENABLED
              value: {{ .Values.redis.enabled | quote }}
              {{- if .Values.redis.enabled }}
            - name: REDIS_HOST
              value: "{{ .Release.Name }}-redis-master"
            - name: REDIS_HOST
              value: "6379"
            - name: REDIS_USERNAME
              value: "default"
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  {{- if .Values.redis.auth.existingSecret}}
                  name: {{ .Values.redis.auth.existingSecret }}
                  {{- else }}
                  name: {{ .Release.Name }}-redis
                  {{- end }}
                  {{- if .Values.redis.auth.existingSecretPasswordKey }}
                  key: {{ .Values.redis.auth.existingSecretPasswordKey }}
                  {{- else }}
                  key: redis-password
                  {{- end }}
              {{- end }}
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "directus.databaseSecretName" . }}
                  {{- if .Values.mariadb.auth.username }}
                  key: mariadb-password
                  {{- else if .Values.mariadb.enabled }}
                  key: mariadb-root-password
                  {{- else }}
                  key: database-password
                  {{- end }}
            - name: ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ template "directus.core" . }}
                  key: ADMIN_PASSWORD
            - name: SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ template "directus.core" . }}
                  key: SECRET
            - name: KEY
              valueFrom:
                secretKeyRef:
                  name: {{ template "directus.core" . }}
                  key: KEY
            - name: PUBLIC_URL
              value: {{ .Values.directus.publicUrl | quote }}
            {{- if .Values.extraEnvVars }}
            {{- tpl (toYaml .Values.extraEnvVars) $ | nindent 12 }}
            {{- end }}
          ports:
            - name: http
              containerPort: 8055
              protocol: TCP
          {{- if .Values.livenessProbe.enabled }}
          livenessProbe:
            {{- toYaml (omit .Values.livenessProbe "enabled") | nindent 12 }}
          {{- end }}
          {{- if .Values.readinessProbe.enabled }}
          readinessProbe:
            {{- toYaml (omit .Values.readinessProbe "enabled") | nindent 12 }}
          {{- end }}
          {{- if .Values.startupProbe.enabled }}
          startupProbe:
            {{- toYaml (omit .Values.startupProbe "enabled") | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            {{- toYaml .Values.extraVolumeMounts | nindent 12 }}
        {{- if .Values.sidecars }}
        {{- include "directus.render" ( dict "value" .Values.sidecars "context" $ ) | nindent 8 }}
        {{- end }}
        {{- if .Values.sidecar.enabled }}
        - name: {{ .Chart.Name }}-sidecar
          image: "{{ .Values.sidecar.repository }}:{{ .Values.sidecar.tag }}"
          imagePullPolicy: {{ .Values.sidecar.pullPolicy }}
          {{- with .Values.sidecar.command }}
          command:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          securityContext:
            {{- toYaml .Values.sidecar.securityContext | nindent 12 }}
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.extraVolumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
