---
{{- if .Release.IsInstall }}
{{- $existingSecret := lookup "v1" "Secret" .Release.Namespace (include "directus.core" .) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "directus.core" . }}
  labels:
    app.kubernetes.io/name: {{ include "directus.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "directus.chart" . }}
    helm.sh/resource-policy: keep
type: Opaque
data:
  ADMIN_PASSWORD: {{ .Values.directus.adminPassword | default (include "directus.secretKeyHelper" (dict "key" "ADMIN_PASSWORD" "data" $existingSecret.data)) | default (randAlphaNum 16) | b64enc | quote }}
  SECRET: {{ .Values.directus.secret | default (include "directus.secretKeyHelper" (dict "key" "SECRET" "data" $existingSecret.data)) | default (randAlphaNum 16) | b64enc | quote }}
  KEY: {{ .Values.directus.key | default (include "directus.secretKeyHelper" (dict "key" "KEY" "data" $existingSecret.data)) | default (randAlphaNum 16) | b64enc | quote }}
{{- end }}
